<?php include "head.php"; ?>



    <nav class="main-nav">
        <ul>
            <li><a class="active main-title" href="anphantomvoices.php">An Phantom Voices</a></li>
            <li><a href="december.php">December</a></li>
            <li><a href="january.php">January</a></li>
            <li><a href="february.php">February</a></li>
            <li><a href="march.php">March</a></li>
            <li><a href="april.php">April</a></li>
            <li><a href="may.php">May</a></li>
            <li><a href="june.php">June</a></li>
        </ul>
    </nav>
</header>

<main class="content--container__basic">
    <div class="content--txt content--left">
        <h3 class="title">AN PHANTOM VOICES</h3>
        <p>Radio is the technology of signaling and communicating using radio waves.Radio waves are electromagnetic waves of frequency between 30 hertz and 300 gigahertz. They are generated by an electronic device called a transmitter connected to an antenna which radiates the waves, and received by a radio receiver connected to another antenna. Radio is very widely used in modern technology, in radio communication, radar, radio navigation, remote control, remote sensing and other applications. In radio communication, used in radio and television broadcasting, cell phones, two-way radios, wireless networking and satellite communication among numerous other
uses, radio waves are used to carry information across space from a transmitter to a receiver, by modulating the radio signal (impressing an information signal on the radio wave by varying some aspect of the wave) in the transmitter. In radar, used to locate and track objects like aircraft, ships, spacecraft and missiles, a beam of radio waves emitted by a radar transmitter reflects off the target object, and the reflected waves reveal the object‘s location. In radio navigation systems such as GPS and VOR, a mobile receiver receives radio signals from na- vigational radio beacons whose position is known, and by precisely measuring the arrival time of the radio waves the receiver can a beam of radio waves emitted by a radar transmitter reflects off the target object, and the reflected waves reveal the object‘s location. In radio navigation systems such as GPS and VOR, a mobile receiver receives radio signals from na- vigational radio beacons whose position is known, and by precisely measuring the arrival time of the radio waves the receiver cana beam of radio waves emitted by a radar transmitter reflects off the target object, and the reflected waves reveal the object‘s location. In radio navigation systems such as GPS and VOR, a mobile receiver receives radio signals from na- vigational radio beacons whose position is known, and by precisely measuring the arrival time of the radio waves the receiver can</p>
    </div>

    <div class="content--txt content--left">
        <h3 class="title">TIMELINE</h3>
        <p>Radio is the technology of signaling and communicating using radio waves.Radio waves are electromagnetic waves of frequency between 30 hertz and 300 gigahertz. They are generated by an electronic device called a transmitter connected to an antenna which radiates the waves, and received by a radio receiver connected to another antenna. Radio is very widely used in modern technology, in radio communication, radar, radio navigation, remote control, remote sensing and other applications. In radio communication, used in radio and television broadcasting, cell phones, two-way radios, wireless networking and satellite communication among numerous other
uses, radio waves are used to carry information across space from a transmitter to a receiver, by modulating the radio signal (impressing an information signal on the radio wave by varying some aspect of the wave) in the transmitter. In radar, used to locate and track objects like aircraft, ships, spacecraft and missiles, a beam of radio waves emitted by a radar transmitter reflects off the target object, and the reflected waves reveal the object‘s location. In radio navigation systems such as GPS and VOR, a mobile receiver receives radio signals from na- vigational radio beacons whose position is known, and by precisely measuring the arrival time of the radio waves the receiver can a beam of radio waves emitted by a radar transmitter reflects off the target object, and the reflected waves reveal the object‘s location. In radio navigation systems such as GPS and VOR, a mobile receiver receives radio signals from na- vigational radio beacons whose position is known, and by precisely measuring the arrival time of the radio waves the receiver cana beam of radio waves emitted by a radar transmitter reflects off the target object, and the reflected waves reveal the object‘s location. In radio navigation systems such as GPS and VOR, a mobile receiver receives radio signals from na- vigational radio beacons whose position is known, and by precisely measuring the arrival time of the radio waves the receiver can</p>
    </div>
</main>

<?php include "footer.php"; ?>
</div> <!-- .end of wrapper -->

<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script src="script.js"></script>

</body>

</html>

