<?php include "head.php";?>
    <div id="p5js-dec" class="canvas-container"></div>
    <div class="full-height">
        <header class="mast-head">

            <nav class="main-nav">
                <ul>
                    <li><a class="main-title" href="anphantomvoices.php">An Phantom Voices</a></li>
                    <li><a class="active" href="december.php">December</a></li>
                    <li><a href="january.php">January</a></li>
                    <li><a href="february.php">February</a></li>
                    <li><a href="march.php">March</a></li>
                    <li><a href="april.php">April</a></li>
                    <li><a href="may.php">May</a></li>
                    <li><a href="june.php">June</a></li>
                </ul>
            </nav>
        </header>
        <main class="content--container">
            <div class="content--left d-flex aic">
                <p>
                    Radio is the technology of signaling and communicating using radio waves. Radio waves are electromagnetic waves of frequen- cy between 30 hertz and 300 gigahertz. They are generated by
                    an electronic device called a transmitter connected to an anten- na which radiates the waves, and received by a radio receiver connected to another antenna. Radio is very widely used in mo- dern technology, in radio communication, radar, radio navigation, remote control, remote sensing and other applications. In radio communication, used in radio and television broadcasting, cell phones, two-way radio
                </p>
            </div>

            <div class="content--right">
                <ul>
                    <li>
                        <a>MARGINS AS THE SILENT SILENCED CENTER</a></li>
                        <li><a>SONIC MEDITATIONS (SINGING WITH THE SIRENS)</a></li>
                        <li>
                            <span>TITLE, Visual Score by MINA MUSTERFRAU</span>
                        </li>
                        <li>
                            <span>TITLE, Broadcast by MALA MUSTERFRAU</span>
                        </li>
                    </ul>
                </div>

            </main>


            <?php include "footer.php"; ?>
        </div>



</div> <!-- .end of wrapper -->

<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>

<script>window.countDownDate = new Date("Dec 02, 2019 12:00").getTime();</script>
<script src="script.js"></script>
<script src="js/p5/dec.js"></script>

</body>

</html>
