<?php include "head.php";?>
    <nav class="main-nav">
        <ul>
            <li><a class="main-title" href="anphantomvoices.php">An Phantom Voices</a></li>
            <li><a href="december.php">December</a></li>
            <li><a class="active" href="january.php">January</a></li>
            <li><a href="february.php">February</a></li>
            <li><a href="march.php">March</a></li>
            <li><a href="april.php">April</a></li>
            <li><a href="may.php">May</a></li>
            <li><a href="june.php">June</a></li>
        </ul>
    </nav>
</header>
<main class="content--container">

    <div id="p5js-dec" class="content--left">

    </div>
    <div class="content--right">
        <ul>
            <li class="grow">
                <button class="accordion--toggle">MARGINS AS THE SILENT SILENCED CENTER</button>
                <div class="panel open">
                    <p class="additional--info">“The Transformation of Silence into Language and Action” from *Your Silence Will Not Protect You* by Audre Lorde.<br><br>
Additional readings: “Silence, Feminism, Power. Reflections at the Edges of Sound.” by Sheena Malhotra, Aimee Carrillo Rowe (Ed.), “Can the Subaltern Speak?” by Gayatri Chakravorty Spi- vak, “Word and Silence” from: “Listening and Voice: Phenome- nologies of Sound” by Don Ihde.</p>
                </div>
            </li>
            <li><button class="accordion--toggle">SONIC MEDITATIONS (SINGING WITH THE SIRENS)</button>
                <div class="panel">
                    5.12.2019 at Werkplaats Typografie
Radio is the technology of signaling and communicating using radio waves.Radio waves are electromagnetic waves of frequency between 30 hertz and 300 gigahertz. They are generated by an electronic device called a transmitter connected to an antenna which radiates the waves, and received by a radio receiver connected to another antenna. Radio is very widely used in modern technology, in radio communication, radar, radio navigation, remote control, remote sensing and other applications. In radio communication, used in radio and television broadcasting, cell phones, two-way radios, wireless networking and satellite communication among numerous other
uses, radio waves are used to carry information across space from a transmitter to a receiver, by modulating the radio signal (impressing an information signal on the radio wave by varying some aspect of the
                </div></li>
            <li>
                <span>TITLE, Visual Score by MINA MUSTERFRAU</span>
            </li>
            <li>
                <span>TITLE, Broadcast by MALA MUSTERFRAU</span>
            </li>
        </ul>
    </div>

</main>

<footer class="content--footer">
    <div class="foot--left">hosted by phantom radio</div>
    <div class="foot--right"><a href="#">Colophon</a></div>
</footer>

</div> <!-- .end of wrapper -->

<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>

<script src="js/p5/index.js"></script>
<script>window.countDownDate = new Date("Jan 06, 2020 12:00").getTime();</script>
<script src="script.js"></script>

</body>

</html>
